global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["20.205.138.251:9090"]
  - job_name: "node"
    static_configs:
      - targets: ["20.205.138.251:9100"]
  - job_name: "ipfs-ac"
    metrics_path: "/debug/metrics/prometheus"
    static_configs:
      - targets: ["20.205.138.251:5001"]
